# 创建服务角色
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-alert-action
  namespace: kube-plugin

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: go-alert-action
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: go-alert-action
  namespace: kube-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: go-alert-action
subjects:
  - kind: ServiceAccount
    name: go-alert-action
    namespace: kube-plugin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-plugin
  name: alert-action
  labels:
    app: alert-action
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alert-action
  template:
    metadata:
      labels:
        app: alert-action
    spec:
      containers:
        - name: alert-action
          image: registry.cn-beijing.aliyuncs.com/sunlge/alert_action:v1alpha1
          imagePullPolicy: Always
          env:
            - name: KUBECONFIG
              value: "${config_path}"
            - name: app.env.TOKEN
              value: "${dingtalk_webhook}"
            - name: app.env.MOBILE
              value: ""
          ports:
            - containerPort: 8090
              protocol: TCP
              name: api
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-plugin
  name: alert-action
  labels:
    app: alert-action
spec:
  ports:
    - port: 8090
      targetPort: 8090
  selector:
    app: alert-action